### ISSUE TITLE
Cannot connect to UvA-BiTS

### ISSUE THREAD

**Issue by peterdesmet** [inbo/bird-tracking#111]
Since a week or so, I can no longer connect to the UvA-BiTS DB using R:

```R
library(tidyverse)
library(here)
library(config)
library(DBI)
library(RPostgres)
library(glue)

uvabits <- config::get("uvabits")
con = dbConnect(
  RPostgres::Postgres(),
  host = uvabits$server,
  port = uvabits$port,
  user = uvabits$username,
  password = uvabits$password,
  dbname = uvabits$database
)

sql <- "SELECT * FROM gps.ee_individual_limited LIMIT 10"
dbGetQuery(con, sql)
```

Results in:

```
Error in connection_create(names(opts), as.vector(opts)) : 
  SSL SYSCALL error: Connection reset by peer
ERROR:  login rejected
```

It works fine for connecting with a local postgres DB.

@stijnvanhoey @damianooldoni could you test this to? Make sure you have a `config.yml` file in the directory structure above your repo (e.g. at the same level as all your repos, with the following structure):

```yaml
default:
  uvabits:
    server: ""
    port: 5432
    username: ""
    password: ""
    database: ""
```
